### ISSUE TITLE
monarch-ontology infores record needs a new URL

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/information-resource-registry#45]
current catalog entry:
```
  - id: infores:monarch-ontology
    status: deprecated
    name: SciGraph-Monarch-Ontology
    xref:
      - scigraph-ontology.monarchinitiative.org/scigraph/docs/
    knowledge_level: other
    agent_type: not_provided
``` 

@kevinschaper - any ideas?  this might need to be deprecated, but should the link instead point to phenio?
